### ISSUE TITLE
Indexing Date Format issue

### ISSUE THREAD

**Issue by kevalkothari** [jlolling/talendcomp_tElasticSearch#4]
Hi @jlolling 

Thanks  for this great component. Hope you are well! 

I managed to index my data into Elastic Search after following your steps.

What I unable to get working is saving Date in Dateformat in Elastic search it always getting inserted as Text string. Any way to fix this?

Input Date in format: ""yyyy-MM-dd HH:mm:ss""

https://www.dropbox.com/s/0l77zoqdb98790x/2020-04-19_19-58-17.png?dl=0

But In Elastic Search That Field becomes Text field

https://www.dropbox.com/s/3fhs3ws97nb79n7/2020-04-19_20-00-10.png?dl=0

Any comment would be appreciated!

**Comment by jlolling** [comment]
Hi, thanks for the kind words.
ElasticSearch stores json documents. Json does not know the type date. Date is always simply text. You can put date values as any pattern as you want with the tJSONDocOutput component. 
Do you expect ElasticSearch supports a special date typed json field?
https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html

**Comment by jlolling** [comment]
Which ElasticSearch version you are running?

**Comment by kevalkothari** [comment]
Hi @jlolling 

Your sentence "Json does not know the type date"  triggered click in my mind  - simply I had to find way to properly send date rather then messing Date type inside Talend Schema 

what I did  is I added one more Tmap and replaced " " space in date with "T"  and it worked 

`row1.date.replace(" ", "T") `

that simply made `2020-04-18 10:46:50`  to `2020-04-18T10:46:50`   and now it works fine.

https://www.dropbox.com/s/9gxifzpp6swrul5/2020-04-19_20-47-16.png?dl=0

Thanks a lot for your help. and I have latest ElasticSearch 7.6.2

Thanks,
Keval

**Comment by jlolling** [comment]
You could put the T also with the pattern! "yyyy-MM-dd'T'HH:mm:ss"

**Comment by kevalkothari** [comment]
Putting directly that produces error as below 

Unparseable date: "2020-04-18 10:46:50"
Unparseable date: "2020-04-18 10:46:50"
Unparseable date: "2020-04-18 10:46:50"
Unparseable date: "2020-04-18 10:46:50"
Unparseable date: "2020-04-18 10:46:50"
Unparseable date: "2020-04-18 10:47:52"
Unparseable date: "2020-04-18 10:47:55"

https://www.dropbox.com/s/xnstz9edsz77ty8/2020-04-19_20-56-30.png?dl=0

**Comment by kevalkothari** [comment]
placed directly in schema 
https://www.dropbox.com/s/mq67pbsxl19e1l5/2020-04-19_20-59-01.png?dl=0

you referring placing it some where else?

**Comment by jlolling** [comment]
Your incoming schema column must be of type Date.
The pattern must be "yyyy-MM-dd'T'HH:mm:ss"
I have just tested it and it works very well.

**Comment by jlolling** [comment]
![demojob](https://user-images.githubusercontent.com/8038781/79697033-94acd180-8280-11ea-9ac3-747adad4e48d.png)
![demojob-result](https://user-images.githubusercontent.com/8038781/79697034-98d8ef00-8280-11ea-970a-f340580dbc2c.png)

**Comment by jlolling** [comment]
This document can be indexed just fine.

**Comment by jlolling** [comment]
I have used a fixed date value to be able to setup a test.

**Comment by jlolling** [comment]
It is not an issue of the elastic search components and also not an issue of the json document.
I would like to close this issue now. If you have further questions, please contact me directly: jan.lolling@gmail.com. I will help you.
Best regards
Jan
